apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nodejs
  sessionAffinity: None