
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EVXdOakl4TkRVeE4xb1hEVE15TURVd016SXhORFV4TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkFSCkFaMFczeGZRbzRzbkxQVWVBVGpkMjdrWlQwR3hlWDRjMEw0bDA0aW5JNlNLQmY4OVYybGdRMWhrdVFpY1plYksKQU83b3poMGxTZkh5d3NNRzRHWTg3WXd3d0UwT0JOcGRCYTRJWXQxeVdRRloxVlFjQTNBL2VIK0lhekJtMStoSgpSTFVUZU1GMi9zSTlkcUJEeHJISEQ2RSt2R3lLWHhVRzVQbTVBMWhjVjAraWlxYUZ6eC9YNHpQMlUrOVRiOUpwCnVWUkh2NkRwUlFPbFpVM1FCdndoZDF5eVlhc0NDWkVPZmVFSTh3VnNERXdRcWpPWGJEMXBqS0xtTVFJL1lDT2QKa09OZE1ycmx5N1NNMXpmZGV0c1BuK1dUR2IxTFlzd2VnUE1USmRoSUFDelVqQ2lieStjQ1hHV09oNVozQTd0aAo0WHNSYUpBb3VtY0ZHTUpYVkJzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEUEZLanRrbWVHQVY1ZzE0VjdrMzZpY0ViUEZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTXd2OTlZWmZicGkzSGZMSGNRcQpkU2VRSWM3d1NmZ2JoVXpoOWU5c2ZSS3Jsc3c5bmxISS9qZ0NXdW40SnkvU0IzdDUwNHJjYyt3N3c0ZFNCMGVNCjh4azRnS1ZYYUE2SHpObEgxVHRVakJKTHpIQ2haeFhsUTdBTjhJelBRSXRyekx6V3I5K2hvYUZWK1lVRDJDZlcKaDhxM3VTZUhNZzJnQVZNVFBzQUVOYmd5ZXhadzB4bm53YUdiQXRMTm1FKzkvcHFhTDFsZDFxTGd0UlVQZ2picwoxYmpqc1hmckNZYnhTQmlwVTh1Nzh6Z0ZmamVocjRPT0pGNlNwWTZIUnNBVzhGZFZLbTVRZ0tHbjRSVWpZOWJqClMzd2tkMFM2TDBLRnlEeDVKVHRWN3F1T25BS0VkZVNlVjNPZng4bW5TYUM0ZDdkbmhaWGorRGE5VVFaaFRDU08KWnJ3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://0ff59061-34c7-449e-9a92-f2be9e0fcd1e.us-southeast-2.linodelke.net:443
  name: lke60147

users:
- name: lke60147-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlYxSE5UYjFkLThHZ2FfeDV2eXBGM1dVenNsNThJRWMxMzlLelk5eDh3THMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tczhydjIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZDBmN2JlMWUtNzIwNC00ODk3LWJkZWYtODk1MjhjZDJhOWE4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.UbZjgzy_uBvbfUgKnjzWXn3517yhjDPzCYtjHkOsrdsmBIFUl4RN5BABWT1xIKrM0bTbpz6TFgx46NemaikVsxLJ8N50m9WJKyBkVdhTxqyZYZc6FYWDTHWQtv-EW8P8UH1NRGepZSfsdgcTFrzTIIBFa9Axa9AKYSbvof6i2NbHZNB65wk0yxYhMD8blgtU2uAx4OWsny4h87dTpOaqWx1jFodrUp7qU9_ER4_Sps24D9_3eXi4j6b5DSHUj6dCQIJ1LypjoTVtWt3_HIx2tLI3_joqPvl8zlDv_jZpEBda9Y1xYcUb1SleIJLjZ7nFfDNA388h6g2tccv71nQJ5Q

contexts:
- context:
    cluster: lke60147
    namespace: default
    user: lke60147-admin
  name: lke60147-ctx

current-context: lke60147-ctx
